                                                                                                                                                                                                                                                                                                                <p>Content for the experience tab goes here.</p>
                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                  )}
                                                                                                                                                                                                                                                                                                                                          {activeTabIndex === 2 && (
                                                                                                                                                                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                                                                                                                                                                <h2>Review & Submit</h2>
                                                                                                                                                                                                                                                                                                                                                                            <p>Content for the review tab goes here.</p>
                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                              )}
                                                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                                                          {/* Navigation Buttons */}
                                                                                                                                                                                                                                                                                                                                                                                                                <div className="tab-navigation">
                                                                                                                                                                                                                                                                                                                                                                                                                        <button onClick={onPrevious} disabled={isFirstTab}>
                                                                                                                                                                                                                                                                                                                                                                                                                                  Previous
                                                                                                                                                                                                                                                                                                                                                                                                                                          </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  <button onClick={onNext} disabled={isLastTab}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                            Next
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                export default Tabs;