                                                                                                                      <input
                                                                                                                                  id="nameInput"
                                                                                                                                              type="text"
                                                                                                                                                          value={name}
                                                                                                                                                                      onChange={(e) => setName(e.target.value)}
                                                                                                                                                                                  required
                                                                                                                                                                                            />
                                                                                                                                                                                                    </div>
                                                                                                                                                                                                            <div>
                                                                                                                                                                                                                      <label htmlFor="messageInput">Message:</label>
                                                                                                                                                                                                                                <textarea
                                                                                                                                                                                                                                            id="messageInput"
                                                                                                                                                                                                                                                        value={message}
                                                                                                                                                                                                                                                                    onChange={(e) => setMessage(e.target.value)}
                                                                                                                                                                                                                                                                                required
                                                                                                                                                                                                                                                                                          />
                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                          <button type="submit">Submit Feedback</button>
                                                                                                                                                                                                                                                                                                                </form>

                                                                                                                                                                                                                                                                                                                      {showToast && (
                                                                                                                                                                                                                                                                                                                              <Toast message={toastMessage} onClose={() => setShowToast(false)} />
                                                                                                                                                                                                                                                                                                                                    )}
                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                          );
                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                          export default App;