                                                                                                                                                                                                                                                                                                      alt={`${profileData.login}'s GitHub profile picture`}
                                                                                                                                                                                                                                                                                                                  style={{ width: '100px', borderRadius: '50%' }}
                                                                                                                                                                                                                                                                                                                            />
                                                                                                                                                                                                                                                                                                                                      <h2>{profileData.name || profileData.login}</h2>
                                                                                                                                                                                                                                                                                                                                                {profileData.bio && <p>{profileData.bio}</p>}
                                                                                                                                                                                                                                                                                                                                                          <p>Followers: {profileData.followers}</p>
                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                        )}
                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                                                              export default GitHubProfileFinder;