                                                                                                                                                                                                                                                                                                                                                      onChange={handleInputChange}
                                                                                                                                                                                                                                                                                                                                                              />
                                                                                                                                                                                                                                                                                                                                                                    </div>

                                                                                                                                                                                                                                                                                                                                                                          <div className="form-group">
                                                                                                                                                                                                                                                                                                                                                                                  <label htmlFor="city">City:</label>
                                                                                                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                                                                                                    type="text"
                                                                                                                                                                                                                                                                                                                                                                                                              id="city"
                                                                                                                                                                                                                                                                                                                                                                                                                        name="city"
                                                                                                                                                                                                                                                                                                                                                                                                                                  value={user.address.city}
                                                                                                                                                                                                                                                                                                                                                                                                                                            onChange={handleInputChange}
                                                                                                                                                                                                                                                                                                                                                                                                                                                    />
                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="profile-preview">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <h3>Live Preview:</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p><strong>Name:</strong> {user.name}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p><strong>Email:</strong> {user.email}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p><strong>Address:</strong> {user.address.street}, {user.address.city}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            export default function App() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              return <ProfileEditor />;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }